# Generated by Django 4.2.19 on 2025-07-29 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remotekitchen', '0012_deliveryfeerule'),
    ]

    operations = [
    ]
