# Generated by Django 4.2.19 on 2025-07-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0181_merge_20250707_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ubereats_requested_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
