# Generated by Django 4.2.19 on 2025-08-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0182_order_ubereats_requested_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="canceled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="canceled_by",
            field=models.CharField(
                blank=True,
                choices=[
                    ("restaurant", "Restaurant"),
                    ("customer", "Customer"),
                    ("admin", "Admin"),
                    ("system", "System"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="canceled_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="cancellation_reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="is_canceled",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="refund_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
