# Generated by Django 4.2.19 on 2025-08-18 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("billing", "0183_orderitem_canceled_at_orderitem_canceled_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiderScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raider_id", models.CharField(max_length=255, unique=True)),
                ("rider_name", models.CharField(blank=True, max_length=255, null=True)),
                ("ratings_count", models.PositiveIntegerField(default=0)),
                ("ratings_sum", models.PositiveIntegerField(default=0)),
                (
                    "rating_avg",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("last_rated_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RiderRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raider_id", models.CharField(db_index=True, max_length=255)),
                ("rider_name", models.CharField(blank=True, max_length=255, null=True)),
                ("stars", models.PositiveSmallIntegerField()),
                ("comment", models.TextField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("is_edited", models.BooleanField(default=False)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rider_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rider_ratings",
                        to="billing.order",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["raider_id", "-created_at"],
                        name="billing_rid_raider__93ad00_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="riderrating",
            constraint=models.UniqueConstraint(
                fields=("order", "customer"),
                name="unique_rider_rating_per_order_customer",
            ),
        ),
    ]
