# Generated by Django 4.2.19 on 2025-07-16 06:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0062_merge_20250714_0046"),
        ("accounts", "0062_merge_20250715_0848"),
    ]

    operations = []
