# Generated by Django 4.2.19 on 2025-07-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0064_usersession_feedbackprompt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userevent",
            name="event_name",
            field=models.CharField(
                choices=[
                    ("app_open", "App Open"),
                    ("app_install", "App Install"),
                    ("onboarding_completed", "Onboarding Completed"),
                    ("order_created", "Order Created"),
                    ("order_completed", "Order Completed"),
                    ("store_clicked", "Store Clicked"),
                    ("cart_abandoned", "Cart Abandoned"),
                    ("referral_shared", "Referral Shared"),
                    ("referral_signup", "Referral Signup"),
                    ("push_sent", "Push Sent"),
                    ("push_clicked", "Push Clicked"),
                    ("spin_invite_clicked", "Spin Invite Clicked"),
                    ("spin_install", "Spin Install"),
                    ("deal_clicked", "Deal Clicked"),
                    ("deal_ordered", "Deal Ordered"),
                ],
                max_length=50,
            ),
        ),
    ]
