# Generated by Django 4.2.19 on 2025-08-06 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0143_merge_20250623_0215"),
        ("accounts", "0065_alter_userevent_event_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="RedZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("center_lat", models.FloatField()),
                ("center_lon", models.FloatField()),
                ("radius_km", models.FloatField(default=1.0)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "allowed_restaurants",
                    models.ManyToManyField(blank=True, to="food.restaurant"),
                ),
            ],
        ),
    ]
