# Generated by Django 4.2.19 on 2025-08-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0065_alter_userevent_event_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_blocked",
            field=models.BooleanField(default=False, verbose_name="Blocked"),
        ),
    ]
