# Generated by Django 4.2.19 on 2025-08-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0066_redzone"),
    ]

    operations = [
        migrations.AddField(
            model_name="redzone",
            name="coverage_area",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
