# Generated by Django 4.2.19 on 2025-08-07 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0066_user_is_blocked'),
        ('accounts', '0067_redzone_coverage_area'),
    ]

    operations = [
    ]
