# Generated by Django 4.2.19 on 2025-08-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_merge_0066_user_is_blocked_0067_redzone_coverage_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redzone',
            name='center_lat',
            field=models.FloatField(verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='redzone',
            name='center_lon',
            field=models.FloatField(verbose_name='Longitude'),
        ),
    ]
