# Generated by Django 4.2.19 on 2025-08-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0069_alter_redzone_center_lat_alter_redzone_center_lon'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickLoginUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('fcm_token', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
