# Generated by Django 4.2.19 on 2025-08-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_quickloginuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickloginuser',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
