# Generated by Django 4.2.19 on 2025-08-07 07:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0071_quickloginuser_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickloginuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quickloginuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Disable to prevent login'),
        ),
        migrations.AddField(
            model_name='quickloginuser',
            name='name',
            field=models.CharField(blank=True, help_text='Full name of the user', max_length=100),
        ),
        migrations.AlterField(
            model_name='quickloginuser',
            name='label',
            field=models.CharField(blank=True, help_text='Optional description or role', max_length=100),
        ),
        migrations.AlterField(
            model_name='quickloginuser',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
