# Generated by Django 4.2.19 on 2025-08-21 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0072_quickloginuser_created_at_quickloginuser_is_active_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userevent",
            name="event_name",
            field=models.CharField(
                choices=[
                    ("app_open", "App Open"),
                    ("app_install", "App Install"),
                    ("onboarding_completed", "Onboarding Completed"),
                    ("order_created", "Order Created"),
                    ("order_completed", "Order Completed"),
                    ("store_clicked", "Store Clicked"),
                    ("cart_abandoned", "Cart Abandoned"),
                    ("referral_shared", "Referral Shared"),
                    ("referral_signup", "Referral Signup"),
                    ("push_sent", "Push Sent"),
                    ("push_clicked", "Push Clicked"),
                    ("spin_invite_clicked", "Spin Invite Clicked"),
                    ("spin_install", "Spin Install"),
                    ("cut", "Cut"),
                    ("reward_redeemed", "Reward Redeemed"),
                    ("item_exchanged", "Item Exchanged"),
                    ("deal_clicked", "Deal Clicked"),
                    ("deal_ordered", "Deal Ordered"),
                ],
                max_length=50,
            ),
        ),
    ]
