# Generated by Django 4.2.19 on 2025-07-17 04:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0025_alter_booking_guest_alter_booking_hotel"),
    ]

    operations = [
        migrations.AddField(
            model_name="hoteltag",
            name="is_seasonal_deal",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hoteltag",
            name="is_special_deal",
            field=models.BooleanField(default=False),
        ),
    ]
