# Generated by Django 4.2.19 on 2025-07-21 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0026_hoteltag_is_seasonal_deal_hoteltag_is_special_deal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomtype",
            name="max_children",
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
