# Generated by Django 4.2.19 on 2025-07-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reward", "0045_notificationlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("reward_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("target_cac", models.DecimalField(decimal_places=2, max_digits=10)),
                ("completion_rate_base", models.FloatField(default=1.0)),
                ("cut_decay_alpha", models.FloatField(default=0.95)),
                ("cut_decay_beta", models.FloatField(default=0.85)),
                ("drop_items", models.JSONField(default=list)),
                ("drop_cycle", models.IntegerField(default=5)),
                ("item_thresholds", models.JSONField(default=dict)),
                ("exchange_rates", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
