# Generated by Django 4.2.19 on 2025-08-22 20:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("reward", "0047_task_rewardredemption_cut"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notificationlog",
            options={"ordering": ["-sent_at"]},
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="error_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="message_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="sent_date_bd",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="sent_time_bd",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="channel",
            field=models.CharField(
                choices=[("push", "push"), ("sms", "sms")], db_index=True, max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="sent_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("sent", "sent"),
                    ("failed", "failed"),
                    ("skipped", "skipped"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="tier",
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
